/**
 * Build a SQL seed file for D1 from the local data/ inventory.
 *
 *   bun run scripts/seed-d1.ts
 *     -> writes web/seed.sql with INSERT statements for:
 *        - docs        (from public/samples/manifest.json)
 *        - qsets       (from data/bench/qsets.json)
 *        - bench_results (from the latest data/bench/results/*.json)
 *
 * Apply with:
 *   bunx wrangler d1 execute eom-data --remote --file seed.sql
 *
 * Idempotent: uses INSERT OR REPLACE so re-runs are safe.
 */

import { existsSync, readFileSync, readdirSync, writeFileSync } from "fs";
import { join } from "path";

const ROOT = join(import.meta.dir, "..", "..");
const MANIFEST = join(import.meta.dir, "..", "public", "samples", "manifest.json");
const QSETS = join(ROOT, "data", "bench", "qsets.json");
const RESULTS_DIR = join(ROOT, "data", "bench", "results");
const OUT = join(import.meta.dir, "..", "seed.sql");

function sqlString(s: string): string {
  return "'" + s.replace(/'/g, "''") + "'";
}

// D1 wraps every statement in an implicit atomic batch; explicit
// BEGIN/COMMIT are rejected. See cloudflare/workers-sdk discussion.
const lines: string[] = [
  "-- Generated by scripts/seed-d1.ts. Do not edit by hand.",
  "-- Re-run with: bun run scripts/seed-d1.ts",
  "",
  "DELETE FROM bench_results;",
  "DELETE FROM qsets;",
  "DELETE FROM docs;",
  "",
];

// docs
const manifest = JSON.parse(readFileSync(MANIFEST, "utf8"));
for (const m of manifest) {
  lines.push(
    `INSERT INTO docs (id, type, slug, title) VALUES (` +
    [m.id, m.type, m.slug, m.title].map(sqlString).join(", ") + `);`
  );
}
lines.push("");

// qsets — the qsets.json doc_id may be a short slug ("paris-2024") whose
// canonical id in docs is "news/paris-2024-olympics". The reliable bridge
// is doc_path: "data/gold/news/paris-2024-olympics" -> id "news/paris-2024-olympics".
function resolveDocId(q: any): string {
  const fromPath = (q.doc_path as string | undefined)
    ?.replace(/^data\/gold\//, "");
  if (fromPath && manifest.find((d: any) => d.id === fromPath)) return fromPath;
  const bySlug = manifest.find((d: any) => d.slug === q.doc_id);
  if (bySlug) return bySlug.id;
  return q.doc_id;
}

const qsetData = JSON.parse(readFileSync(QSETS, "utf8"));
const qsetDocIdByLocalId: Record<string, string> = {};
for (const q of qsetData.qsets) {
  const docId = resolveDocId(q);
  qsetDocIdByLocalId[q.doc_id] = docId;
  q.questions.forEach((qq: any, i: number) => {
    lines.push(
      `INSERT INTO qsets (q_id, doc_id, question, reference, position) VALUES (` +
      [qq.id, docId, qq.q, qq.ref].map(sqlString).join(", ") +
      `, ${i});`
    );
  });
}
lines.push("");

// bench_results — latest run
const resultsFiles = existsSync(RESULTS_DIR)
  ? readdirSync(RESULTS_DIR).filter((f) => f.endsWith(".json")).sort()
  : [];
const latest = resultsFiles[resultsFiles.length - 1];
if (latest) {
  const rows = JSON.parse(readFileSync(join(RESULTS_DIR, latest), "utf8"));
  for (const r of rows) {
    if (r.error) continue;
    // bench_results doc_id matches the qsets local doc_id (e.g. "paris-2024").
    // Resolve via the same map used for qsets.
    const docId = qsetDocIdByLocalId[r.doc_id]
      ?? manifest.find((d: any) => d.slug === r.doc_id)?.id
      ?? r.doc_id;
    const judgeScore = r.judge_score === null || r.judge_score === undefined
      ? "NULL" : String(r.judge_score);
    const judgeRat = r.judge_rationale
      ? sqlString(r.judge_rationale)
      : "NULL";
    const citations = Array.isArray(r.citations) ? r.citations.length : 0;
    lines.push(
      `INSERT INTO bench_results ` +
      `(run_id, doc_id, question_id, mode, model, input_tokens, output_tokens, latency_ms, citations, judge_score, judge_rationale) VALUES (` +
      [r.run_id, docId, r.question_id, r.mode, r.model].map(sqlString).join(", ") +
      `, ${r.input_tokens}, ${r.output_tokens}, ${Math.round((r.latency_s || 0) * 1000)}, ${citations}, ${judgeScore}, ${judgeRat});`
    );
  }
}
lines.push("");

writeFileSync(OUT, lines.join("\n") + "\n");
console.log(`wrote ${OUT}`);
console.log(`  docs: ${manifest.length}`);
console.log(`  qsets: ${qsetData.qsets.reduce((n: number, q: any) => n + q.questions.length, 0)}`);
console.log(`  bench_results: from ${latest || "(none)"}`);
